# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ModifyDetailsPage.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 80, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 150, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 230, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(70, 310, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(290, 20, 261, 20))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.btnDone = QtWidgets.QPushButton(self.centralwidget)
        self.btnDone.setGeometry(QtCore.QRect(380, 470, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnDone.setFont(font)
        self.btnDone.setObjectName("btnDone")
        self.editID = QtWidgets.QTextEdit(self.centralwidget)
        self.editID.setGeometry(QtCore.QRect(300, 80, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.editID.setFont(font)
        self.editID.setObjectName("editID")
        self.editFirst = QtWidgets.QTextEdit(self.centralwidget)
        self.editFirst.setGeometry(QtCore.QRect(300, 150, 261, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.editFirst.setFont(font)
        self.editFirst.setObjectName("editFirst")
        self.editMiddle = QtWidgets.QTextEdit(self.centralwidget)
        self.editMiddle.setGeometry(QtCore.QRect(300, 230, 261, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.editMiddle.setFont(font)
        self.editMiddle.setObjectName("editMiddle")
        self.editLast = QtWidgets.QTextEdit(self.centralwidget)
        self.editLast.setGeometry(QtCore.QRect(300, 310, 261, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.editLast.setFont(font)
        self.editLast.setObjectName("editLast")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "           Faculty ID"))
        self.label_2.setText(_translate("MainWindow", "          First Name"))
        self.label_3.setText(_translate("MainWindow", "          Middle Name"))
        self.label_4.setText(_translate("MainWindow", "           Last Name"))
        self.label_6.setText(_translate("MainWindow", " FACULTY MEMBER DETAILS"))
        self.btnDone.setText(_translate("MainWindow", "DONE"))

